/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kitchenmenneger;

import clientserver.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author comp2
 */
public class ClientKitchen extends javax.swing.JFrame {

    private Client client;

    /**
     * Creates new form ClientKitchen
     */
    public ClientKitchen() {
        initComponents();
        client = new Client();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        AddRice = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AddCake = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AddCookies = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("אורז");

        AddRice.setBackground(new java.awt.Color(204, 204, 255));
        AddRice.setFont(new java.awt.Font("Tekton Pro", 0, 48)); // NOI18N
        AddRice.setForeground(new java.awt.Color(204, 204, 255));
        AddRice.setText("+");
        AddRice.setName(""); // NOI18N
        AddRice.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AddRiceMouseMoved(evt);
            }
        });
        AddRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRiceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("עוגה כושית");

        AddCake.setBackground(new java.awt.Color(204, 204, 255));
        AddCake.setFont(new java.awt.Font("Tekton Pro Cond", 0, 48)); // NOI18N
        AddCake.setForeground(new java.awt.Color(204, 204, 255));
        AddCake.setText("+");
        AddCake.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AddCakeMouseMoved(evt);
            }
        });
        AddCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCakeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("עוגיות");

        AddCookies.setBackground(new java.awt.Color(204, 204, 255));
        AddCookies.setFont(new java.awt.Font("Tekton Pro Cond", 0, 48)); // NOI18N
        AddCookies.setForeground(new java.awt.Color(204, 204, 255));
        AddCookies.setText("+");
        AddCookies.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AddCookiesMouseMoved(evt);
            }
        });
        AddCookies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCookiesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ברוך הבא למטבח.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("לבחירת מתכון לחץ על כפתור ה+ שלידו");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddCookies, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161)
                                .addComponent(AddCake, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(110, 110, 110)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddRice, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(272, 272, 272))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
            .addGroup(layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCake, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCookies, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddRice, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddRiceMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddRiceMouseMoved
        // AddRice.setBackground(Color.yellow);
    }//GEN-LAST:event_AddRiceMouseMoved

    private void AddCakeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCakeMouseMoved
        // AddCake.setBackground(Color.pink);
    }//GEN-LAST:event_AddCakeMouseMoved

    private void AddCookiesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCookiesMouseMoved

    }//GEN-LAST:event_AddCookiesMouseMoved
//הוספת אורז
    private void AddRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRiceActionPerformed

        AddRice.setEnabled(false);
        AddCookies.setEnabled(false);
        AddCake.setEnabled(false);

        jLabel1.setText("מתכון אורז בתהליך הכנה");

        Thread t = new Thread(() -> {
            String res = client.sendNumberAndGetString(1);

            jLabel1.setText("אורז הסתיים בהצלחה");
            AddRice.setEnabled(true);
            AddCookies.setEnabled(true);
            AddCake.setEnabled(true);
        });
        t.start();

    }//GEN-LAST:event_AddRiceActionPerformed
//הוספת עוגה
    private void AddCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCakeActionPerformed
        AddRice.setEnabled(false);
        AddCookies.setEnabled(false);
        AddCake.setEnabled(false);
        jLabel1.setText("עוגה בתהליך הכנה");

        Thread t = new Thread(() -> {
            String res = client.sendNumberAndGetString(2);

            jLabel1.setText("עוגה הסתיימה בהצלחה");
            AddRice.setEnabled(true);
            AddCookies.setEnabled(true);
            AddCake.setEnabled(true);
        });
        t.start();
     }//GEN-LAST:event_AddCakeActionPerformed
//הוספת עוגיות
    private void AddCookiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCookiesActionPerformed
        AddRice.setEnabled(false);
        AddCookies.setEnabled(false);
        AddCake.setEnabled(false);
        jLabel1.setText("עוגיות בתהליך הכנה");

        Thread t = new Thread(() -> {
            String res = client.sendNumberAndGetString(3);
            AddRice.setEnabled(true);
            AddCookies.setEnabled(true);
            AddCake.setEnabled(true);
            jLabel1.setText("עוגיות הסתייימו בהצלחה");
        });
        t.start();

    }//GEN-LAST:event_AddCookiesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientKitchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientKitchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientKitchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientKitchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ClientKitchen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCake;
    private javax.swing.JButton AddCookies;
    private javax.swing.JButton AddRice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
